# Example Site settings
title: anne lee steele # name of the site
author: anne lee steele # name of site's author
email: aleesteele@gmail.com # email of site's author
url: https://aleesteele.com # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - updates.md
footer: 'project page by <a href="https://aleesteele.com/">anne lee steele</a> (@aleesteele)'

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /update/:title

defaults:
  - scope:
      path: ""
      type: blog       # applies to the `blog` collection
    values:
      layout: post
  - scope:
      path: ""
      type: projects   # applies to the `projects` collection
    values:
      layout: post